//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS_HCI_Project_Group_5_Team_B.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMS_HCI_Project_Group_5_Team_B.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the buttons to accept or decline request.
        /// </summary>
        public static string AcceptAndDeclineLabel {
            get {
                return ResourceManager.GetString("AcceptAndDeclineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting request.
        /// </summary>
        public static string AcceptingRequest {
            get {
                return ResourceManager.GetString("AcceptingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to accept the request?.
        /// </summary>
        public static string AcceptionCheck {
            get {
                return ResourceManager.GetString("AcceptionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Reservation Change Request Window.
        /// </summary>
        public static string AcceptReservationChangeRequestWindow {
            get {
                return ResourceManager.GetString("AcceptReservationChangeRequestWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        public static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Location Suggestions Window.
        /// </summary>
        public static string AccommodationLocationSuggestionsWindow {
            get {
                return ResourceManager.GetString("AccommodationLocationSuggestionsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation Window.
        /// </summary>
        public static string AccommodationWindow {
            get {
                return ResourceManager.GetString("AccommodationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Comment.
        /// </summary>
        public static string AdditionalComment {
            get {
                return ResourceManager.GetString("AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Add&apos; button to add accommodation on popular location.
        /// </summary>
        public static string AddOnPopularLocationLabel {
            get {
                return ResourceManager.GetString("AddOnPopularLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available forums.
        /// </summary>
        public static string AvailableForums {
            get {
                return ResourceManager.GetString("AvailableForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busyness.
        /// </summary>
        public static string Busyness {
            get {
                return ResourceManager.GetString("Busyness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Off.
        /// </summary>
        public static string CallOff {
            get {
                return ResourceManager.GetString("CallOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to call of the renovation?.
        /// </summary>
        public static string CallOffCheck {
            get {
                return ResourceManager.GetString("CallOffCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Call off&apos; button to cancel renovation.
        /// </summary>
        public static string CallOffLabel {
            get {
                return ResourceManager.GetString("CallOffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Off Renovation Window.
        /// </summary>
        public static string CallOffRenovationWindow {
            get {
                return ResourceManager.GetString("CallOffRenovationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled reservations.
        /// </summary>
        public static string CancelledReservations {
            get {
                return ResourceManager.GetString("CancelledReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness.
        /// </summary>
        public static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close accommodation.
        /// </summary>
        public static string CloseAccommodation {
            get {
                return ResourceManager.GetString("CloseAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment with the star means that person has accommodation on location.
        /// </summary>
        public static string CommentStarExplanation {
            get {
                return ResourceManager.GetString("CommentStarExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints From Other Guests.
        /// </summary>
        public static string ComplaintsFromOtherGuests {
            get {
                return ResourceManager.GetString("ComplaintsFromOtherGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Payment On Time.
        /// </summary>
        public static string CompletedPaymentOnTime {
            get {
                return ResourceManager.GetString("CompletedPaymentOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline Reservation ChangeRequest Form.
        /// </summary>
        public static string DeclineReservationChangeRequestForm {
            get {
                return ResourceManager.GetString("DeclineReservationChangeRequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declining request.
        /// </summary>
        public static string DecliningRequest {
            get {
                return ResourceManager.GetString("DecliningRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Delete&apos; button to close accommodation on unpopular location.
        /// </summary>
        public static string DeleteOnUnpopularLocationLabel {
            get {
                return ResourceManager.GetString("DeleteOnUnpopularLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Details&apos; button to see detailed view of grades.
        /// </summary>
        public static string DetailsLabel {
            get {
                return ResourceManager.GetString("DetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected number of days.
        /// </summary>
        public static string ExpectedNumberOfDays {
            get {
                return ResourceManager.GetString("ExpectedNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For renovation.
        /// </summary>
        public static string ForRenovation {
            get {
                return ResourceManager.GetString("ForRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Window.
        /// </summary>
        public static string ForumWindow {
            get {
                return ResourceManager.GetString("ForumWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future renovations.
        /// </summary>
        public static string FutureRenovations {
            get {
                return ResourceManager.GetString("FutureRenovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Generate&apos; button to generate reservation report for accommodation.
        /// </summary>
        public static string GenerateLabel {
            get {
                return ResourceManager.GetString("GenerateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Average.
        /// </summary>
        public static string GradeAverage {
            get {
                return ResourceManager.GetString("GradeAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Grade&apos; button to grade a guest.
        /// </summary>
        public static string GradeLabel {
            get {
                return ResourceManager.GetString("GradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades given by guests.
        /// </summary>
        public static string GradesGivenByGuests {
            get {
                return ResourceManager.GetString("GradesGivenByGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grading.
        /// </summary>
        public static string Grading {
            get {
                return ResourceManager.GetString("Grading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grading average.
        /// </summary>
        public static string GradingAverage {
            get {
                return ResourceManager.GetString("GradingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grading Guest Window.
        /// </summary>
        public static string GradingGuestWindow {
            get {
                return ResourceManager.GetString("GradingGuestWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Guests.
        /// </summary>
        public static string MaxGuests {
            get {
                return ResourceManager.GetString("MaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal Reservation Days.
        /// </summary>
        public static string MinReservationDays {
            get {
                return ResourceManager.GetString("MinReservationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Accommodation Statistics Window.
        /// </summary>
        public static string MonthlyAccommodationStatisticsWindow {
            get {
                return ResourceManager.GetString("MonthlyAccommodationStatisticsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly details.
        /// </summary>
        public static string MonthlyDetails {
            get {
                return ResourceManager.GetString("MonthlyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly statistics.
        /// </summary>
        public static string MonthlyStatistics {
            get {
                return ResourceManager.GetString("MonthlyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New accommodation.
        /// </summary>
        public static string NewAccommodation {
            get {
                return ResourceManager.GetString("NewAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Period.
        /// </summary>
        public static string NoticePeriod {
            get {
                return ResourceManager.GetString("NoticePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications you got from guests.
        /// </summary>
        public static string NotificationsFromGuests {
            get {
                return ResourceManager.GetString("NotificationsFromGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of grades.
        /// </summary>
        public static string NumberOfGrades {
            get {
                return ResourceManager.GetString("NumberOfGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Number of reservations.
        /// </summary>
        public static string NumberOfReservations {
            get {
                return ResourceManager.GetString("NumberOfReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional explanation:.
        /// </summary>
        public static string OptionalExplanation {
            get {
                return ResourceManager.GetString("OptionalExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Accommodation Grade Details Window.
        /// </summary>
        public static string OwnerAccommodationGradeDetailsWindow {
            get {
                return ResourceManager.GetString("OwnerAccommodationGradeDetailsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner correctness.
        /// </summary>
        public static string OwnerCorrectness {
            get {
                return ResourceManager.GetString("OwnerCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Window.
        /// </summary>
        public static string OwnerWindow {
            get {
                return ResourceManager.GetString("OwnerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past renovations.
        /// </summary>
        public static string PastRenovations {
            get {
                return ResourceManager.GetString("PastRenovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture URLs.
        /// </summary>
        public static string PictureURLs {
            get {
                return ResourceManager.GetString("PictureURLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal of locations for opening new accommodations.
        /// </summary>
        public static string ProposalOfPopularLocations {
            get {
                return ResourceManager.GetString("ProposalOfPopularLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal of locations for closing existing accommodations.
        /// </summary>
        public static string ProposalOfUnpopularLocations {
            get {
                return ResourceManager.GetString("ProposalOfUnpopularLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quietness.
        /// </summary>
        public static string Quietness {
            get {
                return ResourceManager.GetString("Quietness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended renovation.
        /// </summary>
        public static string RecommendedRenovation {
            get {
                return ResourceManager.GetString("RecommendedRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation.
        /// </summary>
        public static string Renovation {
            get {
                return ResourceManager.GetString("Renovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for changing reservation.
        /// </summary>
        public static string RequestsForChangingReservation {
            get {
                return ResourceManager.GetString("RequestsForChangingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduled.
        /// </summary>
        public static string Rescheduled {
            get {
                return ResourceManager.GetString("Rescheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduled reservations.
        /// </summary>
        public static string RescheduledReservations {
            get {
                return ResourceManager.GetString("RescheduledReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations for grading.
        /// </summary>
        public static string ReservationForGrading {
            get {
                return ResourceManager.GetString("ReservationForGrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules Compliance.
        /// </summary>
        public static string RulesCompliance {
            get {
                return ResourceManager.GetString("RulesCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Schedule&apos; button for scheduling renovation.
        /// </summary>
        public static string ScheduleLabel {
            get {
                return ResourceManager.GetString("ScheduleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Renovation Form.
        /// </summary>
        public static string ScheduleRenovationForm {
            get {
                return ResourceManager.GetString("ScheduleRenovationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Search&apos; button to see available dates.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Show&apos; button to see comments on forum.
        /// </summary>
        public static string ShowLabel {
            get {
                return ResourceManager.GetString("ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Statistics.
        /// </summary>
        public static string ShowStatistics {
            get {
                return ResourceManager.GetString("ShowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose accommodation you want the statistics for and then click on &apos;Show statistics&apos; button.
        /// </summary>
        public static string ShowStatisticsLabel {
            get {
                return ResourceManager.GetString("ShowStatisticsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star symbolizes that forum is very useful.
        /// </summary>
        public static string StarForumExplanation {
            get {
                return ResourceManager.GetString("StarForumExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month marked with the star was the busiest.
        /// </summary>
        public static string StarMonthExplanation {
            get {
                return ResourceManager.GetString("StarMonthExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year marked with the star was the busiest.
        /// </summary>
        public static string StarYearExplanation {
            get {
                return ResourceManager.GetString("StarYearExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Of Inventory.
        /// </summary>
        public static string StateOfInventory {
            get {
                return ResourceManager.GetString("StateOfInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions for new location.
        /// </summary>
        public static string SuggestionsForNewLocation {
            get {
                return ResourceManager.GetString("SuggestionsForNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are super-owner your accommodation will be shown first to the guests.
        /// </summary>
        public static string SuperOwnerExplanation {
            get {
                return ResourceManager.GetString("SuperOwnerExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range ending time.
        /// </summary>
        public static string TimeRangeEndingTime {
            get {
                return ResourceManager.GetString("TimeRangeEndingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time range starting time.
        /// </summary>
        public static string TimeRangeStartingTime {
            get {
                return ResourceManager.GetString("TimeRangeStartingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful.
        /// </summary>
        public static string Useful {
            get {
                return ResourceManager.GetString("Useful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted end date.
        /// </summary>
        public static string WantedEndDate {
            get {
                return ResourceManager.GetString("WantedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted start date.
        /// </summary>
        public static string WantedStartDate {
            get {
                return ResourceManager.GetString("WantedStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly statistics.
        /// </summary>
        public static string YearlyStatistics {
            get {
                return ResourceManager.GetString("YearlyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Accommodations.
        /// </summary>
        public static string YourAccommodations {
            get {
                return ResourceManager.GetString("YourAccommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your notifications.
        /// </summary>
        public static string YourNotifications {
            get {
                return ResourceManager.GetString("YourNotifications", resourceCulture);
            }
        }
    }
}
